name: .NET Tests on Windows Self-Hosted Runner

on:
  push:
    branches: [ master ]  # or 'main' if that’s your branch
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image (CMD)
        run: docker build -t my-dotnet-app .
        shell: cmd

      - name: Run Tests in Docker Container (CMD)
        run: docker run --rm my-dotnet-app
        shell: cmd
